---

- name: Potos preparation playbook
  hosts: localhost
  connection: local
  become: True
  gather_facts: False
  ignore_errors: False

  pre_tasks:
    - name: read specs repo configuration
      ansible.builtin.include_vars:
        file: '/etc/potos/specs_repo.yml'
        name: potos_specs
    - name: Get specs repo for {{ potos_specs.client_name }}
      ansible.builtin.git:
        repo: '{{ potos_specs.git_url }}/{{ potos_specs.git_repo }}.git'
        dest: '{{ playbook_dir }}/specs'
        version: '{{ potos_specs.git_branch }}'
      changed_when: False
      failed_when: False
  tasks:
    - name: Check if specs exists
      ansible.builtin.stat:
        path: '{{ playbook_dir }}/specs'
      register: check_potos_specs

    - name: Error handling
      ansible.builtin.debug:
        msg: 'Unable to find an potos specs repo for {{ potos_specs.client_name }}'
      when: not check_potos_specs.stat.exists

    - name: Configure playbook for {{ potos_client_name }} with specs
      when: check_potos_specs.stat.exists
      block:

        - name: Get templates
          ansible.builtin.find:
            path: '{{ playbook_dir }}/specs/templates'
            recurse: yes
            file_type: file
          register: potos_playbook_specs_templates

        - name: Create parent dir for templates
          ansible.builtin.file:
            path: '{{ item | regex_replace("^(.*?)\/specs\/templates(.*?)(\.j2)$", "\1\2") | dirname}}'
            state: 'directory'
            recurse: yes
          loop: '{{ potos_playbook_specs_templates.files | map(attribute="path") | list }}'

        - name: Apply templates
          ansible.builtin.template:
            src: '{{ item }}'
            dest: '{{ item | regex_replace("^(.*?)\/specs\/templates(.*?)(\.j2)$", "\1\2") }}'
          loop: '{{ potos_playbook_specs_templates.files | map(attribute="path") | list }}'

        - name: Get files to copy
          ansible.builtin.find:
            path: '{{ playbook_dir }}/specs/files'
            recurse: yes
            file_type: file
          register: potos_playbook_specs_files

        - name: Create parent dir for files
          ansible.builtin.file:
            path: '{{ item | regex_replace("^(.*?)\/specs\/files(.*?)$", "\1\2") | dirname}}'
            state: 'directory'
            recurse: yes
          loop: '{{ potos_playbook_specs_files.files | map(attribute="path") | list }}'

        - name: Copy files
          ansible.builtin.copy:
            src: '{{ item }}'
            dest: '{{ item | regex_replace("^(.*?)\/specs\/files(.*?)$", "\1\2") }}'
          loop: '{{ potos_playbook_specs_files.files | map(attribute="path") | list }}'

        - name: Get vars to copy
          ansible.builtin.find:
            path: '{{ playbook_dir }}/specs/vars'
            recurse: yes
            file_type: file
          register: potos_playbook_specs_vars

        - name: Create parent dir for vars
          ansible.builtin.file:
            path: '{{ item | regex_replace("^(.*?)\/specs\/vars(.*?)$", "\1/host_vars/localhost\2") | dirname}}'
            state: 'directory'
            recurse: yes
          loop: '{{ potos_playbook_specs_vars.files | map(attribute="path") | list }}'

        - name: Copy vars
          ansible.builtin.copy:
            src: '{{ item }}'
            dest: '{{ item | regex_replace("^(.*?)\/specs\/vars(.*?)$", "\1/host_vars/localhost\2") }}'
          loop: '{{ potos_playbook_specs_vars.files | map(attribute="path") | list }}'

        - name: Install required collections
          ansible.builtin.command:
            cmd: 'ansible-galaxy collection install -r collections.yml -p /etc/ansible/collections'
            chdir: '{{ playbook_dir }}'
          changed_when: False

      rescue:
        - name: Error handling
          ansible.builtin.debug:
            msg: 'Error while deploying {{ potos_client_name }} ansible vars'
