---

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: ghcr.io/projectpotos/${MOLECULE_DISTRO}-ansible-test:latest
    pre_build_image: yes
    command: /lib/systemd/systemd
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

verifier:
  name: ansible
